# Generated by Django 2.2.4 on 2020-02-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=50)),
                ('file_hash', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_veri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('veri_code', models.CharField(max_length=50)),
            ],
        ),
    ]
